M48
; DRILL file {KiCad 6.0.6+dfsg-1~bpo11+1} date Sat 12 Nov 2022 03:24:32 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-12T15:24:32-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X157.55Y-32.8
X157.55Y-41.2
X159.0Y-76.3
X159.0Y-86.3
X159.0Y-96.3
X159.0Y-106.3
T2
X80.5Y-49.25
X80.5Y-98.25
X138.5Y-49.25
X138.5Y-98.25
T0
M30
